services:
  db:
    environment:
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: root
    image: postgres:15.8-alpine3.20
    ports:
    - 5432:5432
    restart: always
  go_app_dev:
    build:
      context: ./golang/
      dockerfile: Dockerfile
    environment:
      DEBUG: "true"
      POSTGRES_DB: converter
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: "5432"
      POSTGRES_SSLMODE: disable
      POSTGRES_USER: postgres
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672/
      CONVERSION_EXCHANGE: conversion_exchange
      CONVERSION_QUEUE: video_conversion_queue
      CONVERSION_KEY: conversion
    stdin_open: true
    tty: true
    volumes:
    - .:/app
    - external-storage:/media/uploads
  pgadmin:
    depends_on:
    - db
    environment:
      PGADMIN_DEFAULT_EMAIL: luisotaviodesimone@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    image: dpage/pgadmin4:8.11.0
    ports:
    - 5050:80
    restart: always
  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_USER: admin
    image: rabbitmq:3-management
    ports:
    - 5672:5672
    - 15672:15672
volumes:
  external-storage:
    external: true
