# Generated by Django 5.1.4 on 2024-12-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_video_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(upload_to="thumbnails/", verbose_name="Thumbnail"),
        ),
    ]
